name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: ilammy/setup-nasm@v1
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: wallpaper-aligner
        path: target/release/*.exe
